---
title: "Analysis of Casco BAy WWTF Discharges"
output: html_notebook
---

#Load libraries
```{r}
library(tidyverse)
```

#Load Data
```{r}
the.data <- read.delim("Total Discharge.txt", sep = '\t', colClasses = c('factor', 'character', 'numeric', 'numeric'))
colnames(the.data)[3:4]<- c('Avg', 'Max')



months <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
monthNums <- sapply(substr(the.data$Report.date,1,3), function(x) which(months==x))

the.data$Date <- as.Date(paste('15/',monthNums,'/20',substr(the.data$Report.date, 5,6), sep = ''),  '%d/%m/%Y')
the.data$Year <- as.numeric(paste('20', substr(the.data$Report.date, 5,6), sep = ''))
the.data$Month <- factor(substr(the.data$Report.date,1,3), levels = months)
summary(the.data)
```


```{r}
plt <- ggplot(the.data) + aes(Date,Avg, color = Site) + geom_line() + scale_y_log10()
plt
```

```{r}
plt <- ggplot(the.data) + aes(as.numeric(Month),Avg, color = Site) + geom_point() + geom_smooth()
plt <- plt + scale_y_log10() + scale_x_continuous(limits=c(1,12), breaks = c(3,6,9,12))
plt <- plt + xlab('Month') + ylab('Average Daily Discharge (MG)')
plt
```

#What data do we have available?

```{r}
table(the.data$Month, the.data$Year)

```

So, we have slightly more than two years of continuous discharge data for all sites.

# Extract full 2017 Calendar Year

Approximate daily annual averages ( not weighted for number of days in the month)
```{r}
tapply(the.data$Avg[the.data$Year == 2017], the.data$Site[the.data$Year == 2017], mean, na.omit = TRUE)
```

# Calculate Annual Totals
```{r}
monthdays <- c(31, 28, 31, 30,31,30, 31, 31, 30, 31, 30, 31)
tmp <- the.data %>% filter(Year == 2017) %>% mutate(MonthTot= Avg * monthdays[as.numeric(Month)])
annualdata<- tmp %>% select(Site, Avg, MonthTot) %>% group_by(Site) %>% summarise(Annual = sum(MonthTot, na.omit = TRUE))
rm(tmp)
```



